/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTenantRouteImport } from './routes/app.$tenant'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantRoute = AppTenantRouteImport.update({
  id: '/app/$tenant',
  path: '/app/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRoute
  '/app/$tenant': typeof AppTenantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRoute
  '/app/$tenant': typeof AppTenantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform': typeof PlatformRoute
  '/app/$tenant': typeof AppTenantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/platform' | '/app/$tenant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/platform' | '/app/$tenant'
  id: '__root__' | '/' | '/platform' | '/app/$tenant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformRoute: typeof PlatformRoute
  AppTenantRoute: typeof AppTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$tenant': {
      id: '/app/$tenant'
      path: '/app/$tenant'
      fullPath: '/app/$tenant'
      preLoaderRoute: typeof AppTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformRoute: PlatformRoute,
  AppTenantRoute: AppTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
