/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformTenantsRouteImport } from './routes/platform.tenants'
import { Route as PlatformSystemRouteImport } from './routes/platform.system'
import { Route as PlatformSupportRouteImport } from './routes/platform.support'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformSalesRouteImport } from './routes/platform.sales'
import { Route as PlatformPlansRouteImport } from './routes/platform.plans'
import { Route as PlatformMembersRouteImport } from './routes/platform.members'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform.analytics'
import { Route as AppTenantRouteImport } from './routes/app.$tenant'
import { Route as AppTenantIndexRouteImport } from './routes/app.$tenant.index'
import { Route as AppTenantTicketsRouteImport } from './routes/app.$tenant.tickets'
import { Route as AppTenantSetupRouteImport } from './routes/app.$tenant.setup'
import { Route as AppTenantSettingsRouteImport } from './routes/app.$tenant.settings'
import { Route as AppTenantReservationsRouteImport } from './routes/app.$tenant.reservations'
import { Route as AppTenantOrdersRouteImport } from './routes/app.$tenant.orders'
import { Route as AppTenantMembersRouteImport } from './routes/app.$tenant.members'
import { Route as AppTenantIntegrationsRouteImport } from './routes/app.$tenant.integrations'
import { Route as AppTenantInboxRouteImport } from './routes/app.$tenant.inbox'
import { Route as AppTenantCustomersRouteImport } from './routes/app.$tenant.customers'
import { Route as AppTenantApprovalsRouteImport } from './routes/app.$tenant.approvals'
import { Route as AppTenantAnalyticsRouteImport } from './routes/app.$tenant.analytics'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformTenantsRoute = PlatformTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSystemRoute = PlatformSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSalesRoute = PlatformSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformMembersRoute = PlatformMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PlatformRoute,
} as any)
const AppTenantRoute = AppTenantRouteImport.update({
  id: '/app/$tenant',
  path: '/app/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantIndexRoute = AppTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantTicketsRoute = AppTenantTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantSetupRoute = AppTenantSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantSettingsRoute = AppTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantReservationsRoute = AppTenantReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantOrdersRoute = AppTenantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantMembersRoute = AppTenantMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantIntegrationsRoute = AppTenantIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantInboxRoute = AppTenantInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantCustomersRoute = AppTenantCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantApprovalsRoute = AppTenantApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppTenantRoute,
} as any)
const AppTenantAnalyticsRoute = AppTenantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppTenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/app/$tenant': typeof AppTenantRouteWithChildren
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/members': typeof PlatformMembersRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/sales': typeof PlatformSalesRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/system': typeof PlatformSystemRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/platform/': typeof PlatformIndexRoute
  '/app/$tenant/analytics': typeof AppTenantAnalyticsRoute
  '/app/$tenant/approvals': typeof AppTenantApprovalsRoute
  '/app/$tenant/customers': typeof AppTenantCustomersRoute
  '/app/$tenant/inbox': typeof AppTenantInboxRoute
  '/app/$tenant/integrations': typeof AppTenantIntegrationsRoute
  '/app/$tenant/members': typeof AppTenantMembersRoute
  '/app/$tenant/orders': typeof AppTenantOrdersRoute
  '/app/$tenant/reservations': typeof AppTenantReservationsRoute
  '/app/$tenant/settings': typeof AppTenantSettingsRoute
  '/app/$tenant/setup': typeof AppTenantSetupRoute
  '/app/$tenant/tickets': typeof AppTenantTicketsRoute
  '/app/$tenant/': typeof AppTenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/members': typeof PlatformMembersRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/sales': typeof PlatformSalesRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/system': typeof PlatformSystemRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/platform': typeof PlatformIndexRoute
  '/app/$tenant/analytics': typeof AppTenantAnalyticsRoute
  '/app/$tenant/approvals': typeof AppTenantApprovalsRoute
  '/app/$tenant/customers': typeof AppTenantCustomersRoute
  '/app/$tenant/inbox': typeof AppTenantInboxRoute
  '/app/$tenant/integrations': typeof AppTenantIntegrationsRoute
  '/app/$tenant/members': typeof AppTenantMembersRoute
  '/app/$tenant/orders': typeof AppTenantOrdersRoute
  '/app/$tenant/reservations': typeof AppTenantReservationsRoute
  '/app/$tenant/settings': typeof AppTenantSettingsRoute
  '/app/$tenant/setup': typeof AppTenantSetupRoute
  '/app/$tenant/tickets': typeof AppTenantTicketsRoute
  '/app/$tenant': typeof AppTenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/app/$tenant': typeof AppTenantRouteWithChildren
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/members': typeof PlatformMembersRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/sales': typeof PlatformSalesRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/system': typeof PlatformSystemRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/platform/': typeof PlatformIndexRoute
  '/app/$tenant/analytics': typeof AppTenantAnalyticsRoute
  '/app/$tenant/approvals': typeof AppTenantApprovalsRoute
  '/app/$tenant/customers': typeof AppTenantCustomersRoute
  '/app/$tenant/inbox': typeof AppTenantInboxRoute
  '/app/$tenant/integrations': typeof AppTenantIntegrationsRoute
  '/app/$tenant/members': typeof AppTenantMembersRoute
  '/app/$tenant/orders': typeof AppTenantOrdersRoute
  '/app/$tenant/reservations': typeof AppTenantReservationsRoute
  '/app/$tenant/settings': typeof AppTenantSettingsRoute
  '/app/$tenant/setup': typeof AppTenantSetupRoute
  '/app/$tenant/tickets': typeof AppTenantTicketsRoute
  '/app/$tenant/': typeof AppTenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/app/$tenant'
    | '/platform/analytics'
    | '/platform/members'
    | '/platform/plans'
    | '/platform/sales'
    | '/platform/settings'
    | '/platform/support'
    | '/platform/system'
    | '/platform/tenants'
    | '/platform/'
    | '/app/$tenant/analytics'
    | '/app/$tenant/approvals'
    | '/app/$tenant/customers'
    | '/app/$tenant/inbox'
    | '/app/$tenant/integrations'
    | '/app/$tenant/members'
    | '/app/$tenant/orders'
    | '/app/$tenant/reservations'
    | '/app/$tenant/settings'
    | '/app/$tenant/setup'
    | '/app/$tenant/tickets'
    | '/app/$tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform/analytics'
    | '/platform/members'
    | '/platform/plans'
    | '/platform/sales'
    | '/platform/settings'
    | '/platform/support'
    | '/platform/system'
    | '/platform/tenants'
    | '/platform'
    | '/app/$tenant/analytics'
    | '/app/$tenant/approvals'
    | '/app/$tenant/customers'
    | '/app/$tenant/inbox'
    | '/app/$tenant/integrations'
    | '/app/$tenant/members'
    | '/app/$tenant/orders'
    | '/app/$tenant/reservations'
    | '/app/$tenant/settings'
    | '/app/$tenant/setup'
    | '/app/$tenant/tickets'
    | '/app/$tenant'
  id:
    | '__root__'
    | '/'
    | '/platform'
    | '/app/$tenant'
    | '/platform/analytics'
    | '/platform/members'
    | '/platform/plans'
    | '/platform/sales'
    | '/platform/settings'
    | '/platform/support'
    | '/platform/system'
    | '/platform/tenants'
    | '/platform/'
    | '/app/$tenant/analytics'
    | '/app/$tenant/approvals'
    | '/app/$tenant/customers'
    | '/app/$tenant/inbox'
    | '/app/$tenant/integrations'
    | '/app/$tenant/members'
    | '/app/$tenant/orders'
    | '/app/$tenant/reservations'
    | '/app/$tenant/settings'
    | '/app/$tenant/setup'
    | '/app/$tenant/tickets'
    | '/app/$tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  AppTenantRoute: typeof AppTenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/tenants': {
      id: '/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformTenantsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/system': {
      id: '/platform/system'
      path: '/system'
      fullPath: '/platform/system'
      preLoaderRoute: typeof PlatformSystemRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/support': {
      id: '/platform/support'
      path: '/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof PlatformSupportRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/sales': {
      id: '/platform/sales'
      path: '/sales'
      fullPath: '/platform/sales'
      preLoaderRoute: typeof PlatformSalesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/plans': {
      id: '/platform/plans'
      path: '/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/members': {
      id: '/platform/members'
      path: '/members'
      fullPath: '/platform/members'
      preLoaderRoute: typeof PlatformMembersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/app/$tenant': {
      id: '/app/$tenant'
      path: '/app/$tenant'
      fullPath: '/app/$tenant'
      preLoaderRoute: typeof AppTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$tenant/': {
      id: '/app/$tenant/'
      path: '/'
      fullPath: '/app/$tenant/'
      preLoaderRoute: typeof AppTenantIndexRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/tickets': {
      id: '/app/$tenant/tickets'
      path: '/tickets'
      fullPath: '/app/$tenant/tickets'
      preLoaderRoute: typeof AppTenantTicketsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/setup': {
      id: '/app/$tenant/setup'
      path: '/setup'
      fullPath: '/app/$tenant/setup'
      preLoaderRoute: typeof AppTenantSetupRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/settings': {
      id: '/app/$tenant/settings'
      path: '/settings'
      fullPath: '/app/$tenant/settings'
      preLoaderRoute: typeof AppTenantSettingsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/reservations': {
      id: '/app/$tenant/reservations'
      path: '/reservations'
      fullPath: '/app/$tenant/reservations'
      preLoaderRoute: typeof AppTenantReservationsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/orders': {
      id: '/app/$tenant/orders'
      path: '/orders'
      fullPath: '/app/$tenant/orders'
      preLoaderRoute: typeof AppTenantOrdersRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/members': {
      id: '/app/$tenant/members'
      path: '/members'
      fullPath: '/app/$tenant/members'
      preLoaderRoute: typeof AppTenantMembersRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/integrations': {
      id: '/app/$tenant/integrations'
      path: '/integrations'
      fullPath: '/app/$tenant/integrations'
      preLoaderRoute: typeof AppTenantIntegrationsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/inbox': {
      id: '/app/$tenant/inbox'
      path: '/inbox'
      fullPath: '/app/$tenant/inbox'
      preLoaderRoute: typeof AppTenantInboxRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/customers': {
      id: '/app/$tenant/customers'
      path: '/customers'
      fullPath: '/app/$tenant/customers'
      preLoaderRoute: typeof AppTenantCustomersRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/approvals': {
      id: '/app/$tenant/approvals'
      path: '/approvals'
      fullPath: '/app/$tenant/approvals'
      preLoaderRoute: typeof AppTenantApprovalsRouteImport
      parentRoute: typeof AppTenantRoute
    }
    '/app/$tenant/analytics': {
      id: '/app/$tenant/analytics'
      path: '/analytics'
      fullPath: '/app/$tenant/analytics'
      preLoaderRoute: typeof AppTenantAnalyticsRouteImport
      parentRoute: typeof AppTenantRoute
    }
  }
}

interface PlatformRouteChildren {
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformMembersRoute: typeof PlatformMembersRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformSalesRoute: typeof PlatformSalesRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformSupportRoute: typeof PlatformSupportRoute
  PlatformSystemRoute: typeof PlatformSystemRoute
  PlatformTenantsRoute: typeof PlatformTenantsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  PlatformMembersRoute: PlatformMembersRoute,
  PlatformPlansRoute: PlatformPlansRoute,
  PlatformSalesRoute: PlatformSalesRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformSupportRoute: PlatformSupportRoute,
  PlatformSystemRoute: PlatformSystemRoute,
  PlatformTenantsRoute: PlatformTenantsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface AppTenantRouteChildren {
  AppTenantAnalyticsRoute: typeof AppTenantAnalyticsRoute
  AppTenantApprovalsRoute: typeof AppTenantApprovalsRoute
  AppTenantCustomersRoute: typeof AppTenantCustomersRoute
  AppTenantInboxRoute: typeof AppTenantInboxRoute
  AppTenantIntegrationsRoute: typeof AppTenantIntegrationsRoute
  AppTenantMembersRoute: typeof AppTenantMembersRoute
  AppTenantOrdersRoute: typeof AppTenantOrdersRoute
  AppTenantReservationsRoute: typeof AppTenantReservationsRoute
  AppTenantSettingsRoute: typeof AppTenantSettingsRoute
  AppTenantSetupRoute: typeof AppTenantSetupRoute
  AppTenantTicketsRoute: typeof AppTenantTicketsRoute
  AppTenantIndexRoute: typeof AppTenantIndexRoute
}

const AppTenantRouteChildren: AppTenantRouteChildren = {
  AppTenantAnalyticsRoute: AppTenantAnalyticsRoute,
  AppTenantApprovalsRoute: AppTenantApprovalsRoute,
  AppTenantCustomersRoute: AppTenantCustomersRoute,
  AppTenantInboxRoute: AppTenantInboxRoute,
  AppTenantIntegrationsRoute: AppTenantIntegrationsRoute,
  AppTenantMembersRoute: AppTenantMembersRoute,
  AppTenantOrdersRoute: AppTenantOrdersRoute,
  AppTenantReservationsRoute: AppTenantReservationsRoute,
  AppTenantSettingsRoute: AppTenantSettingsRoute,
  AppTenantSetupRoute: AppTenantSetupRoute,
  AppTenantTicketsRoute: AppTenantTicketsRoute,
  AppTenantIndexRoute: AppTenantIndexRoute,
}

const AppTenantRouteWithChildren = AppTenantRoute._addFileChildren(
  AppTenantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformRoute: PlatformRouteWithChildren,
  AppTenantRoute: AppTenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
